# Generated by Django 6.1.1 on 2026-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=20)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Wedding Planning", "Wedding Planning"),
                            ("Birthday Celebrations", "Birthday Celebrations"),
                            ("Engagement & Pre-Wedding", "Engagement & Pre-Wedding"),
                            ("Corporate Events", "Corporate Events"),
                            ("Private Parties", "Private Parties"),
                            ("Event Decoration", "Event Decoration"),
                        ],
                        max_length=100,
                    ),
                ),
                ("event_date", models.DateField()),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "event_types",
                    models.CharField(
                        choices=[
                            ("Wedding Planning", "Wedding Planning"),
                            ("Birthday Celebrations", "Birthday Celebrations"),
                            ("Engagement & Pre-Wedding", "Engagement & Pre-Wedding"),
                            ("Corporate Events", "Corporate Events"),
                            ("Private Parties", "Private Parties"),
                            ("Event Decoration", "Event Decoration"),
                        ],
                        max_length=100,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
