# Generated by Django 6.1.1 on 2026-09-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactenquiry",
            old_name="event_date",
            new_name="eventdate",
        ),
    ]
