# Generated by Django 6.1.1 on 2026-09-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_event_date_contactenquiry_eventdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactenquiry",
            old_name="contact",
            new_name="contact_number",
        ),
        migrations.RenameField(
            model_name="contactenquiry",
            old_name="eventdate",
            new_name="event_date",
        ),
        migrations.RenameField(
            model_name="contactenquiry",
            old_name="event_type",
            new_name="event_types",
        ),
    ]
