# Generated by Django 6.1.1 on 2026-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_contact_contactenquiry_contact_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="gallery/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding"),
                            ("destination", "Destination"),
                            ("birthday", "Birthday"),
                            ("anniversary", "Anniversary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
