# Generated by Django 6.1.1 on 2026-09-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactenquiry",
            name="event_types",
        ),
        migrations.RemoveField(
            model_name="eventbooking",
            name="event_types",
        ),
        migrations.RemoveField(
            model_name="galleryimage",
            name="category",
        ),
        migrations.RemoveField(
            model_name="service",
            name="event_types",
        ),
        migrations.AddField(
            model_name="contactenquiry",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enquiries",
                to="events.service",
            ),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="events.service",
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="events.service",
            ),
        ),
    ]
