# Generated by Django 6.1.1 on 2026-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_contactenquiry_event_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
