# Generated by Django 6.1.1 on 2026-10-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_contactenquiry_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventbooking",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wedding", "Wedding"),
                    ("Engagement", "Engagement"),
                    ("Reception Party", "Reception Party"),
                    ("Anniversary", "Anniversary"),
                    ("Birthday Celebration", "Birthday Celebration"),
                    ("Baby Shower", "Baby Shower"),
                    ("Themed Parties", "Themed Parties"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactenquiry",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wedding", "Wedding"),
                    ("Engagement", "Engagement"),
                    ("Reception Party", "Reception Party"),
                    ("Anniversary", "Anniversary"),
                    ("Birthday Celebration", "Birthday Celebration"),
                    ("Baby Shower", "Baby Shower"),
                    ("Themed Parties", "Themed Parties"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="GalleryImage",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
